### ISSUE TITLE
Stuck after a fall bag

### ISSUE THREAD

**Issue by samoletik1337** [jason-e/rngfix#2]
Soucemod version : 1.10.0.6343
Game : CSS:OB
map : bhop_superdooperhard_speedrun
plugin : "RNGFix" (1.1.1) by rio

After falling from a height I can get stuck in the floor, it does not happen on all maps. Disabling rngfix takes care of the issue .

https://youtu.be/6_AH8O3n_Xw

**Comment by jason-e** [comment]
Thanks for reporting this, I've implemented a fix.
