### ISSUE TITLE
rngfix breaking boosterfix

### ISSUE THREAD

**Issue by nanawuu** [jason-e/rngfix#5]
this breaks boosterfix plugin on css by not being able to toggle it on/off. even if u toggle the plugin off u will be still affected by the boosterfix. sucks because some maps are just not beatable with boosterfix plugin turned on and boosters on some maps are completely random without it :/

**Comment by jason-e** [comment]
Can you give me some specific examples of boosters on specific maps? Also please link me the exact boosterfix plugin you are talking about.

**Comment by nanawuu** [comment]
i can't replicate the issue again which is weird x: ill be testing the plugin on a server and report here if the issue comes up again and here's the plugin if you are interested:) https://forums.alliedmods.net/showthread.php?p=2275379

**Comment by nanawuu** [comment]
im closing this issue since there seems to be no issue anymore ^^
