### ISSUE TITLE
Native "TR_EnumerateEntitiesHull" was not found

### ISSUE THREAD

**Issue by RED4911** [jason-e/rngfix#7]
L 04/09/2019 - 05:05:13: SourceMod error session started
L 04/09/2019 - 05:05:13: Info (map "bhop_eazy_v3_beta5") (file "errors_20190409.log")
L 04/09/2019 - 05:05:13: [SM] Unable to load plugin "rngfix.smx": Native "TR_EnumerateEntitiesHull" was not found
L 04/09/2019 - 05:05:17: [SM] Exception reported: Array index out-of-bounds (index 10, limit 7)
L 04/09/2019 - 05:05:17: [SM] Blaming: btimes_20/bTimes-zones.smx
L 04/09/2019 - 05:05:17: [SM] Call stack trace:
L 04/09/2019 - 05:05:17: [SM]   [1] Line 1720, D:\csgo\csgo\addons\sourcemod\scripting\bTimes-zones.sp::LoadZones_Callback
L 04/09/2019 - 05:25:24: Error log file session closed.

**Comment by jason-e** [comment]
Make sure you've read the dependencies list. You need a newer version of SourceMod.
